---
- name: web1
  group: "[webservers]"
  box: ubuntu/bionic64
  ram: 512
  ip: 192.168.17.11

- name: web2
  group: "[webservers]"
  box: ubuntu/bionic64
  ram: 512
  ip: 192.168.17.12

- name: loadbalancer
  group: "[loadbalancers]"
  box: ubuntu/bionic64
  ram: 1024
  ip: 192.168.17.10
